### ISSUE TITLE
Import Hash#dig from facets

### ISSUE THREAD

**Issue by cielavenir** [marcandre/backports#102]
We should add Hash#dig to backports 2.3.0. Actually I'm going to remove Hash#fetch_nested in facets.
https://github.com/rubyworks/facets/blob/master/lib/core/facets/hash/fetch_nested.rb

**Comment by marcandre** [comment]
Would be nice to add.
My biggest issue is the RubyGems mess created when the previous versions were removed... Not too sure how to handle that tbh.

**Comment by marcandre** [comment]
Added `dig` in e36ae38de561111663a8f8d6b4628b35b4fd88e1
