### ISSUE TITLE
getting error  json -v '1.8.6' not installed

### ISSUE THREAD

**Issue by Preeti-qa** [marcandre/backports#105]
While executing command as "bundle install" i am getting error as "An error occurred while installing json (1.8.6), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.6'` succeeds before bundling."
On running command "`gem install json -v '1.8.6'" m getting error as 
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
The system cannot find the path specified.
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

    C:/Environment/Ruby22-x64/bin/ruby.exe extconf.rb
creating Makefile

Gem files will remain installed in C:/Environment/Ruby22-x64/lib/ruby/gems/2.2.0
/gems/json-1.8.6 for inspection.
Results logged to C:/Environment/Ruby22-x64/lib/ruby/gems/2.2.0/gems/json-1.8.6/
ext/json/ext/generator/gem_make.out

Please help!
M running calabash over eclipse and executing command within calabash workplace, on window 8.1 ruby installed version 2.2.6

**Comment by marcandre** [comment]
I am not sure why you are opening an issue with the `backports` gem when you are failing to install the `json` gem.
Good luck.

**Comment by Preeti-qa** [comment]
ok! @marcandre how can I install this gem json  1.8.6 then? it is not allowing me to install bundle 😓
