### ISSUE TITLE
Is try compatible with the rails try?

### ISSUE THREAD

**Issue by bakku** [marcandre/backports#115]
I don't think that the `try` version is compatible with the one from rails.

e.g.

```
$ irb
> require "active_support/all"
> "s".try { |s| s.upcase }   # => "S"

$ irb
> require "backports"
> "s".try { |s| s.upcase }   # => ArgumentError (wrong number of arguments (given 0, expected 1+))
```

Is there a reason why the backports version does not support the handling of a block?

**Comment by marcandre** [comment]
Thanks for the report. Sorry about that. Probably just an old implementation.

Fixed. Note that I recommend avoiding `require 'backports'`; target a particular version, or require only the backports you use.

**Comment by bakku** [comment]
Thanks very much! Sadly it's sinatra that does the `require 'backports'` 😅

https://github.com/sinatra/sinatra/blob/5074c1e342a2472b16ff8ffcd5b2e12f9388da42/sinatra-contrib/lib/sinatra/contrib/setup.rb#L3

**Comment by marcandre** [comment]
Thanks for that, I inquired as to why this is.
