### ISSUE TITLE
String#codepoints as in Ruby 2.x

### ISSUE THREAD

**Issue by sos4nt** [marcandre/backports#129]
The backports gem provides an implementation for the 1.9.1 version of `String#codepoints`. But its behavior changed in [Ruby 2.0.0](https://github.com/ruby/ruby/blob/ruby_2_0_0/NEWS):

> String#codepoints now returns an array instead of an enumerator.

```ruby
# backports
'ABC'.codepoints #=> #<Enumerator: "ABC":codepoints>

# Ruby 1.9.x
'ABC'.codepoints #=> #<Enumerator: "ABC":codepoints>

# Ruby 2.x
'ABC'.codepoints #=> [65, 66, 67]
```

It would be nice if we could also get the latter via backports. Maybe by providing a `backports/2.0.0/string/codepoints` in addition to [`backports/1.9.1/string/codepoints`](https://github.com/marcandre/backports/blob/master/lib/backports/1.9.1/string/codepoints.rb).

**Comment by marcandre** [comment]
Right, I probably should have handled this at the time.

Now it's not clear if handling this would help or hinder. How did you stumble upon this? Do you actually use `backports` and Ruby 1.x?

**Comment by marcandre** [comment]
Next major version will drop support for Ruby < 2.2 (unless someone convinces me otherwise).

Closing this (ditto)
