### ISSUE TITLE
Support for Ruby2.7?

### ISSUE THREAD

**Issue by utkarsh2102** [marcandre/backports#138]
Hi,

Ruby2.7 was released in December 2019 and it'd be great if we can have that support here.
Any plans or ETA for the same?

**Comment by marcandre** [comment]
Glad `backports` is useful for you :-)

We're making good progress, hopefully #136 will land in the next few days.

**Comment by utkarsh2102** [comment]
Hi @marcandre,
Thanks for the quick response.
I hope it lands soon because we're migrating from Ruby2.5 to Ruby2.7 in Debian and currently it fails to build against it :)

**Comment by marcandre** [comment]
It has been merged and released. Hope it resolves your issue

**Comment by utkarsh2102** [comment]
@marcandre, thank you so much!
This is superb! :D
