### ISSUE TITLE
"Require just the needed backports instead"

### ISSUE THREAD

**Issue by zverok** [marcandre/backports#142]
Hey @marcandre!

First thing first: I totally realize that you are the owner of the project and all the final decisions about goals, design and encouraged/discouraged uses is totally your call.

That being said, I believe that deprecating `require 'backports/latest'` (and similar shortcuts) is actually harmful to backports (and, therefore, new features) adoption and appreciation.

Being bold, I'd say there are no major drawbacks of just using all backports that are available, except for possible performance implications -- which would be as true for "some" backports, as for "all" of them. 

"Paying for what you don't actually use" _could_ be a problem (e.g. have `Hash#to_h` proxied through Ruby code even if you don't use block form), but I believe clearly stating it in README and having "require all" as an **opt-in** (which is already done) is enough for grown-ups to decide by themselves if they are ready to trade _possible_ performance problems for convenience without being "punished" for this decision with warnings (and, later, impossibility to just say "OK, I am over 21 year and understand what I am doing, can I please just have everything from 2.7 that is possible?").

The drawback of cherry-picking features is the feedback loop is really discouraging. 
> `sequence.to_h { ... }` -- ugh, doesn't work. OK, it was introduced in 2.6 probably... Oh, OK, `require 'backports/2.6/to_h'`... Umm, not it... OK, then `backports/2.6.0/enumerable/to_h`! Doesn't work?.. Oh, also `backports/2.6.0/array/to_h` :rage: 

As a significant part of backports is "small but nice" features (because larger ones, like semi-open ranges or pattern-matching, are unbackportable without some [transpiler](https://github.com/ruby-next)), we end out with "Ugh, tried that backports thing, but it is too complicated", and adoption of new Ruby features much later than it could've happened.

WDYT?

**Comment by marcandre** [comment]
Thanks for the inquiry.

My thoughts are that:
* As an official feature, I can't break compatibility of `backports/latest` without a major release. I made different bad decisions in the past (rails "backports", patching std lib) which I want to remove in the next versions. Maybe there aren't any additional bad decisions though? 😅
* I'd prefer nobody uses `backports/latest` in production. There have been forward incompatibilities in the past, and while I realize that it can be a tedious exercise to list all the backports, it makes it easy to remove those require when a Ruby version is later dropped (e.g. if a gem decides to drop support for Ruby 2.3.x, then all the `backports/2.3.0/...` can also be dropped.

OTOH, `to_h` and many other `Enumerable` features can be very tedious.

It could be best to link all `to_h` backports together, either implicitly, or via a `require 'backports/to_h'`

**Comment by marcandre** [comment]
Just to be clear, I'd like to know: do you want to use `latest` in production? Or just for scripts?

**Comment by zverok** [comment]
> Just to be clear, I'd like to know: do you want to use `latest` in production? Or just for scripts?

Not only want but actually do :) Our (Verbit.ai) use-case is as follows:
1. We typically ~1 version behind Ruby (e.g. currently we are on 2.6.x)
2. We have tons of algorithmically non-trivial code, which changes fast and should be maintainable, so we use every trick in existance to make code as short (**and clear**) as possible, including all new Ruby features that makes it shorter and more expressive
3. While understanding all the possible forward incompatibilities, we'd prefer to make it our responsibility, not something that is decided for us. 
4. (As you've probably noticed, I am seriously involved in Ruby development currently, so I always strive for "let me use it finally" :))

That's one of my hats (and, well, this case can be easily solved by "I know everything that is new in a new version, I can just insert 10 `require`s).

As a gem author, I am typically very picky about backports. For "just useful library"-class gems I am typically cherry-picking, and typically only those that add new methods (`Kernel#then` :heart_eyes:), not redefine the behavior of existing ones. 

But for more experimental and 0.0.1-level gems, I also start with `backports/latest` to "at least for now, not think which of my favorite tools are available at which Ruby version". I believe this approach also may work for prototype-stage startups with high-level (or just geeky) Rubyists: "we value _velocity_ at this stage, so give us all the good things" (but available dev. or prod. env not ready for Ruby 2.7, say).

As a lecturer/educator, I do a lot for promoting more idiomatic Ruby, including the newest features, including advice about "if you wanna _play_ with this or that example with whatever Ruby version at hands, you just take a backports". And the "role" I see here for backports is to make new features friendlier and more accessible. I don't believe your typical Rubyist will be glad (= willing to use new features) if each of them should be required method-by-method, that's different here than for Python community for example.

So, my point, probably, is:
* promote the responsible approach of cherry-picking _in stable production_,
* but not punish for "give 'em all!" approach for other use-cases.

**Comment by marcandre** [comment]
So instead of "deprecating" that API, I could issue a warning (in verbose mode only, probably?) that this is not recommended for production / general use, and make sure that is clear in the docs too.

WDYT?

**Comment by zverok** [comment]
>  I could issue a warning (in verbose mode only, probably?) that this is not recommended for production / general use, and make sure that is clear in the docs too.

Yes, that would make me much happier :) (And yes, I believe warning should be only in verbose mode, some reporting script with a useful output which always starts its output with warning is ... less desirable)

**Comment by marcandre** [comment]
Done. Thanks a lot for the constructive feedback!
