### ISSUE TITLE
Range#cover? accepts a Range after 2.6

### ISSUE THREAD

**Issue by headius** [marcandre/backports#145]
`Range#cover?`  accepts a Range object in 2.6 and higher.

This is not currently implemented in backports.

**Comment by marcandre** [comment]
Oh, thanks, I'm on it :-)

**Comment by headius** [comment]
We make a checklist out of NEWS for each Ruby version... Here is the JRuby issue for 2.6: https://github.com/jruby/jruby/pull/6037

The specs also show a bunch of other Range behaviors not explicitly called out in NEWS, mostly regarding endless ranges (hard to support in backports since it requires parser changes).
FWIW I swiped your Proc/Method #<< and #>> today and still ship a version of Lazy I think you wrote 😃 Many new features are fine for us in pure Ruby (we can go native later if perf demands it) so if you ever feel like adding missing features...

**Comment by headius** [comment]
Oops that should have been jruby/jruby#5576

**Comment by marcandre** [comment]
Right, I'm adding some missing Rubyspecs for endless ranges...

In theory Endless ranges could be written without parser changes (as `Range.new(1, nil)`) but would be still not be quite supportable.

**Comment by marcandre** [comment]
Done and released (but forgot to close this 😆)
