### ISSUE TITLE
installation of package ‘backports’ had non-zero exit status

### ISSUE THREAD

**Issue by crebli** [marcandre/backports#151]
installation of package ‘backports’ had non-zero exit status
R 3.6.3 or R4.0.0, win10
or  download the 1.1.8.tar.gz:
installation of package ‘C:/Users/user/Desktop/backports_1.1.8.tar.gz’ had non-zero exit status

**Comment by marcandre** [comment]
I'm sorry you're having trouble... This repo is for the *Ruby gem* called "backports". I think you are trying to install something different, but I don't know what. FYI, there has never existed a version 1.1.8 of the gem.
