### ISSUE TITLE
Add missing numerable#filter, Enumerable#filter!, Enumerable#select! to ruby 2.6

### ISSUE THREAD

**Issue by zw963** [marcandre/backports#167]
Please check this blog.

numerable#filter, Enumerable#filter!, Enumerable#select!

Thank you.

**Comment by marcandre** [comment]
Hasn't `Enumerable#filter` always existed?

There are no methods `Enumerable#filter!` and `Enumerable#select!`

**Comment by SeanLF** [comment]
Seems like it's an alias https://www.bigbinary.com/blog/ruby-2-6-adds-enumerable-filter-as-an-alias-of-enumerable-select
