### ISSUE TITLE
Flaky test: test_filter(FilteredQueueTest)

### ISSUE THREAD

**Issue by dleidert** [marcandre/backports#168]
I have seen this test fail sometimes. It failed again in our CI:

```
===============================================================================
Failure: test_filter(FilteredQueueTest)
/builds/ruby-team/ruby-backports/debian/output/source_dir/test/filtered_queue_test.rb:69:in `block in test_filter'
     66:       other.each { |i| @q << i }
     67:       sleep(0.1)
     68:       assert_equal 3, @q.num_waiting
  => 69:       assert_equal 3 * 4, calls
     70:       @q << :extra
     71:       sleep(0.1)
     72:       assert_equal 3 * 5, calls
/builds/ruby-team/ruby-backports/debian/output/source_dir/test/filtered_queue_test.rb:56:in `each'
/builds/ruby-team/ruby-backports/debian/output/source_dir/test/filtered_queue_test.rb:56:in `test_filter'
<12> expected but was
<9>
===============================================================================
```

<https://salsa.debian.org/ruby-team/ruby-backports/-/jobs/2151627> (in a previous run locally it reported 10 instead of 12)

Ruby version is 2.7.

**Comment by dleidert** [comment]
Re-ran the job and it succeeded: <https://salsa.debian.org/ruby-team/ruby-backports/-/jobs/2151727>. Any idea what could cause this test to fail sometimes?

**Comment by marcandre** [comment]
Thanks for reporting this. The test is really not pretty 😅. In particular it does `sleep(0.1)` to insure that the processing in other threads has finished. I should rewrite the condition so it waits until the success condition is reached, or fail after a longer timeout. Hopefully that will resolve the sporadic failure you are encountering.
I hope to work on this in the next few days; please ping me if I don't 😅

**Comment by marcandre** [comment]
I merged a change to the test that aims to resolve the flakiness.
I imagine that you are running the tests from the `master` branch of the repo itself, but if you need a release please let me know.
If you notice a failure again, please let me know and I'll see what I can do 🤞

**Comment by dleidert** [comment]
Thanks for the quick reaction. I applied your patch to the Debian package. This issue has been appearing only a few times. Let's see if it reappears.
