### ISSUE TITLE
Accept a patch to fix Method#to_proc bug under MRI 1.8.7 ?

### ISSUE THREAD

**Issue by dkubb** [marcandre/backports#66]
It appears there is a bug with Method#to_proc under 1.8.7 in MRI, eg:

``` ruby
def foo(arg); p arg; end
foo([])  # => []
method(:foo).call([])  # => []
method(:foo).to_proc.call([]) # => ArgumentError: wrong number of arguments (0 for 1)
```

The same code works fine on yarv, and jruby/rbx in 1.8 mode.

I was wondering if you'd accept a patch to fix this bug? I currently have some conditional logic to handle it in my own libs, but I'd prefer that backports adds the fix so I don't have to conditionally patch ruby.

**Comment by marcandre** [comment]
Closing, 1.8.7 not being a priority at this point...
