### ISSUE TITLE
Backports 3.6.0 broken with Ruby 2.2.0

### ISSUE THREAD

**Issue by mohawkjohn** [marcandre/backports#91]
I get the following error on Mac OS X:

```
$ pry
[1] pry(main)> require "backports"
Errno::EBADF: Bad file descriptor @ fptr_finalize - /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backports-3.6.0/lib/backports/1.9.1/io/open.rb
from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/backports-3.6.0/lib/backports/
```

This happens using IRB also.

```
$ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
```

**Comment by marcandre** [comment]
Sorry for your troubles.
This has already been reported (#86) and fixed, you just need to update. It's always a good idea to do so before reporting a bug too :-)

**Comment by mohawkjohn** [comment]
I apologize. I thought I had!

**Comment by mohawkjohn** [comment]
I apologize. I saw that bug report and thought I'd updated backports already.

**Comment by marcandre** [comment]
No problem, I'm sorry I cause the bug in the first place :+1:
