### ISSUE TITLE
Error in `combine_mode_and_option`

### ISSUE THREAD

**Issue by aaronpk** [marcandre/backports#92]
In backports 2.7.0:

I'm getting an error `undefined method '[]' for nil:NilClass` in tools.rb line 269 "combine_mode_and_option". Reading the code, I believe it's possible for `options` to be nil, so that accessing `options[:mode]` throws this error.

```
def self.combine_mode_and_option(mode = nil, options = Backports::Undefined)
    # Can't backport autoclose, {internal|external|}encoding
    mode, options = nil, mode if mode.is_a?(Hash) and options == Backports::Undefined
    options = {} if options == Backports::Undefined
    if mode && options[:mode]
      raise ArgumentError, "mode specified twice"
    end
    ...
```

If the method is called with `options = nil`, then nothing else will ever set it to a hash or anything else. This causes the line `options[:mode]` to throw the error. I believe this can be fixed by changing the line to 

```
options = {} if options == Backports::Undefined or options == nil
```

**Comment by marcandre** [comment]
Thanks for all the details.

Version 2.7.0 is ancient, though, current version is 3.6.4!

Can you check if you have the same issue with the latest release? Also, which backported method are you calling?

**Comment by aaronpk** [comment]
Yeah I realized it was ancient after I ran a `bundle update`. It looks like 3.6.4 has the fix already:

```
options = {} if options == nil || options == Backports::Undefined
```

I got myself into a weird state with this, so I'm not entirely sure why backports was being called at all, since it wasn't even in my Gemfile. Anyway I guess this is a non-issue, thanks anyway!
