### ISSUE TITLE
Array#sample on 1.9.1 (?) and 1.9.2 only takes one argument

### ISSUE THREAD

**Issue by dwo** [marcandre/backports#94]
I was working on an idea today: https://github.com/songkick/array_deterministic_sample

I noticed that my Travis builds failed on Ruby 1.9.2 because that implementation of `Array#sample` only takes one argument. Did the option to pass in options like `:random => Random.new` only get added in 1.9.3? 

If so, is there a way that backports can redefine the `Array#sample` method on Ruby 1.9.1-1.9.2? Currently the sample backport begins with `unless Array.method_defined? :sample`.

I understand if this a wontfix, I'll just update my README to reflect that my gem won't work on ruby 1.9.1 and 1.9.2

**Comment by marcandre** [comment]
Yes, I think the second was option was added later on.

We could definitely backport that too. I don't know if there are any specs written though.

Care to write a pull request?

**Comment by dwo** [comment]
If there is some precedent for this in code I could use as a guide? I could take a stab at it.

Personally, I don't absolutely need this on 1.9.1 & 1.9.2. At the very least I could word a caveat about the differences between these ruby versions, perhaps?
