### ISSUE TITLE
Range#bsearch looks broken with Float

### ISSUE THREAD

**Issue by cielavenir** [marcandre/backports#97]
https://github.com/marcandre/backports/blob/master/lib/backports/2.0.0/range/bsearch.rb#L19

Do you mean from.to_f?

**Comment by marcandre** [comment]
Indeed! Thanks for the "patch" :smile:

**Comment by marcandre** [comment]
(Forgot to put reference to issue in d212bf27c72652bf0b051b07aca86a24c405133e)
