### ISSUE TITLE
Is it dead?

### ISSUE THREAD

**Issue by zverok** [marcandre/backports#98]
Is this project dead or superceded by something? 
It still seems really useful, but lacks new features from 2.2 and 2.3.
Should they be contributed or no one cares any more?..

**Comment by marcandre** [comment]
Good question :smile:  I've indeed not backported newer features, but I'd be more than willing to accept PRs.

The main difficulty in backporting features is getting every corner case right ([I talked about that](http://confreaks.tv/videos/rubyconf2013-ruby-core-dilemmas))

One issue is that `backports` based tests on RubySpec (which is partly why I contributed so much to RubySpec). But RubySpec removed all/most version dependant specs (unilaterally and against my pleas) :imp:.  So I can't upgrade RubySpec without removing the bulk of the tests for previous versions. Maybe the current rubyspec could be installed as a seperate submodule that could be kept up to date? Or else manually copy/adapt the specs?

**Comment by marcandre** [comment]
So, the short answer is 'no', I'll be closing this.

**Comment by zverok** [comment]
Ok, got it, thanks. I'll try to investigate the possiblities to contribute in following month. I am assured backports SHOULD be alive and I'll faithfully try to do something about it.

One question: I've take a quick look inside RubySpec, and I see language version tags, for ex., here: https://github.com/ruby/spec/blob/master/core/array/dig_spec.rb#L3 or here: https://github.com/ruby/spec/blob/master/core/array/to_h_spec.rb#L4

Is it removed in some other places? Or what did you mean under "RubySpec removed all/most version dependant specs"?

**Comment by marcandre** [comment]
Brixen removed version guards end of '13 - beginning of '14. Gald to see you'll find version afterwards, but nothing for older versions though. E.g. https://github.com/ruby/spec/commit/c625d0cadf73969c16f8422eb9113b1fd0b24a43

**Comment by zverok** [comment]
Huh, I see. Maybe now, when brixen have been retired from spec suite development, and new teem seems a bit more negotiation inclined, those tags can be returned?.

**Comment by marcandre** [comment]
Possible. I'm not sure that mspec is still 1.8.x compatible.
Maybe we can not worry about 1.8.x, since there shouldn't be changes in the future.

**Comment by marcandre** [comment]
I now use two different versions of Rubyspec, the older one frozen for 1.8.x and have backported some of the newer versions.
