### ISSUE TITLE
Test with ruby 2.3.0

### ISSUE THREAD

**Issue by v0dro** [marcandre/backports#99]

**Comment by v0dro** [comment]
The `Prime` class has been removed from ruby 2.3.0, so you might want to reflect that in the gem.

**Comment by marcandre** [comment]
I update lib/prime, thanks!

**Comment by v0dro** [comment]
When do you plan to release a new version? We're using this at SciRuby and could use it to stop our CI builds from failing.

**Comment by marcandre** [comment]
Already done :smile:

**Comment by v0dro** [comment]
thanks!
